/*
 * gen-locales — convert the legacy public/lang/summernote-*.js i18n files (jQuery $.extend data)
 * into typed TS modules under packages/core/src/lang/locales/, plus a barrel registry.
 *
 * The legacy files are `$.extend(true, $.summernote.lang, { 'xx-XX': { ...pure data... } })`.
 * We extract the object literal (brace-balanced, string-aware), eval it as pure data (no jQuery
 * refs inside the lang object), and emit one module per locale + a `locales.ts` registry.
 *
 * Run: node scripts/gen-locales.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, 'public', 'lang');
const outDir = join(root, 'packages', 'core', 'src', 'lang', 'locales');
mkdirSync(outDir, { recursive: true });

/** capture the brace-balanced object literal starting at the first `{` after `marker`. */
function extractObjectLiteral(text, marker) {
  const start = text.indexOf(marker);
  if (start < 0) return null;
  let i = text.indexOf('{', start + marker.length);
  if (i < 0) return null;
  const begin = i;
  let depth = 0;
  let inStr = null; // quote char while inside a string
  for (; i < text.length; i++) {
    const c = text[i];
    if (inStr) {
      if (c === '\\') {
        i++; // skip escaped char
      } else if (c === inStr) {
        inStr = null;
      }
      continue;
    }
    if (c === '"' || c === "'" || c === '`') {
      inStr = c;
    } else if (c === '{') {
      depth++;
    } else if (c === '}') {
      depth--;
      if (depth === 0) {
        return text.slice(begin, i + 1);
      }
    }
  }
  return null;
}

const files = readdirSync(srcDir).filter((f) => /^summernote-.+\.js$/.test(f));
const codes = [];

for (const file of files) {
  const text = readFileSync(join(srcDir, file), 'utf8');
  const literal = extractObjectLiteral(text, '$.summernote.lang');
  if (!literal) {
    console.warn(`skip ${file}: no lang object found`);
    continue;
  }
  let obj;
  try {
    // pure-data object literal; eval in an isolated function scope
    obj = new Function(`return (${literal});`)();
  } catch (e) {
    console.warn(`skip ${file}: eval failed (${e.message})`);
    continue;
  }
  const keys = Object.keys(obj);
  if (keys.length === 0) {
    console.warn(`skip ${file}: empty`);
    continue;
  }
  // use the FILENAME code (unique; e.g. sr-RS vs sr-RS-Latin both key 'sr-RS' internally)
  const code = file.replace(/^summernote-/, '').replace(/\.js$/, '');
  const data = obj[keys[0]];
  codes.push(code);

  const body = `import type { LangPartial } from '../en-US';\n\nconst lang: LangPartial = ${JSON.stringify(
    data,
    null,
    2,
  )};\n\nexport default lang;\n`;
  writeFileSync(join(outDir, `${code}.ts`), body, 'utf8');
}

codes.sort();
const importLines = codes.map((c) => `import ${ident(c)} from './locales/${c}';`).join('\n');
const mapLines = codes.map((c) => `  '${c}': ${ident(c)},`).join('\n');
const barrel = `/* AUTO-GENERATED by scripts/gen-locales.mjs — do not edit by hand. */
import type { LangPartial } from './en-US';
${importLines}

/**
 * All bundled locales as deep-partial overrides of en-US. Import this for the full set, or import a
 * single module directly for tree-shaking, e.g. \`import koKR from '@summernote/core/lang/locales/ko-KR'\`.
 */
export const locales: Record<string, LangPartial> = {
${mapLines}
};

export const localeCodes = Object.keys(locales);
`;
writeFileSync(join(root, 'packages', 'core', 'src', 'lang', 'locales.ts'), barrel, 'utf8');

function ident(code) {
  return 'l_' + code.replace(/[^a-zA-Z0-9]/g, '_');
}

console.log(`generated ${codes.length} locales -> packages/core/src/lang/locales/ + locales.ts`);
