/* AUTO-GENERATED by scripts/gen-locales.mjs — do not edit by hand. */
import type { LangPartial } from './en-US';
import l_ar_AR from './locales/ar-AR';
import l_az_AZ from './locales/az-AZ';
import l_bg_BG from './locales/bg-BG';
import l_bn_BD from './locales/bn-BD';
import l_ca_ES from './locales/ca-ES';
import l_cs_CZ from './locales/cs-CZ';
import l_da_DK from './locales/da-DK';
import l_de_CH from './locales/de-CH';
import l_de_DE from './locales/de-DE';
import l_el_GR from './locales/el-GR';
import l_es_ES from './locales/es-ES';
import l_es_EU from './locales/es-EU';
import l_fa_IR from './locales/fa-IR';
import l_fi_FI from './locales/fi-FI';
import l_fr_FR from './locales/fr-FR';
import l_gl_ES from './locales/gl-ES';
import l_he_IL from './locales/he-IL';
import l_hr_HR from './locales/hr-HR';
import l_hu_HU from './locales/hu-HU';
import l_id_ID from './locales/id-ID';
import l_it_IT from './locales/it-IT';
import l_ja_JP from './locales/ja-JP';
import l_ko_KR from './locales/ko-KR';
import l_lt_LT from './locales/lt-LT';
import l_lt_LV from './locales/lt-LV';
import l_mn_MN from './locales/mn-MN';
import l_nb_NO from './locales/nb-NO';
import l_nl_NL from './locales/nl-NL';
import l_pl_PL from './locales/pl-PL';
import l_pt_BR from './locales/pt-BR';
import l_pt_PT from './locales/pt-PT';
import l_ro_RO from './locales/ro-RO';
import l_ru_RU from './locales/ru-RU';
import l_sk_SK from './locales/sk-SK';
import l_sl_SI from './locales/sl-SI';
import l_sr_RS from './locales/sr-RS';
import l_sr_RS_Latin from './locales/sr-RS-Latin';
import l_sv_SE from './locales/sv-SE';
import l_ta_IN from './locales/ta-IN';
import l_th_TH from './locales/th-TH';
import l_tr_TR from './locales/tr-TR';
import l_uk_UA from './locales/uk-UA';
import l_uz_UZ from './locales/uz-UZ';
import l_vi_VN from './locales/vi-VN';
import l_zh_CN from './locales/zh-CN';
import l_zh_TW from './locales/zh-TW';

/**
 * All bundled locales as deep-partial overrides of en-US. Import this for the full set, or import a
 * single module directly for tree-shaking, e.g. `import koKR from '@summernote/core/lang/locales/ko-KR'`.
 */
export const locales: Record<string, LangPartial> = {
  'ar-AR': l_ar_AR,
  'az-AZ': l_az_AZ,
  'bg-BG': l_bg_BG,
  'bn-BD': l_bn_BD,
  'ca-ES': l_ca_ES,
  'cs-CZ': l_cs_CZ,
  'da-DK': l_da_DK,
  'de-CH': l_de_CH,
  'de-DE': l_de_DE,
  'el-GR': l_el_GR,
  'es-ES': l_es_ES,
  'es-EU': l_es_EU,
  'fa-IR': l_fa_IR,
  'fi-FI': l_fi_FI,
  'fr-FR': l_fr_FR,
  'gl-ES': l_gl_ES,
  'he-IL': l_he_IL,
  'hr-HR': l_hr_HR,
  'hu-HU': l_hu_HU,
  'id-ID': l_id_ID,
  'it-IT': l_it_IT,
  'ja-JP': l_ja_JP,
  'ko-KR': l_ko_KR,
  'lt-LT': l_lt_LT,
  'lt-LV': l_lt_LV,
  'mn-MN': l_mn_MN,
  'nb-NO': l_nb_NO,
  'nl-NL': l_nl_NL,
  'pl-PL': l_pl_PL,
  'pt-BR': l_pt_BR,
  'pt-PT': l_pt_PT,
  'ro-RO': l_ro_RO,
  'ru-RU': l_ru_RU,
  'sk-SK': l_sk_SK,
  'sl-SI': l_sl_SI,
  'sr-RS': l_sr_RS,
  'sr-RS-Latin': l_sr_RS_Latin,
  'sv-SE': l_sv_SE,
  'ta-IN': l_ta_IN,
  'th-TH': l_th_TH,
  'tr-TR': l_tr_TR,
  'uk-UA': l_uk_UA,
  'uz-UZ': l_uz_UZ,
  'vi-VN': l_vi_VN,
  'zh-CN': l_zh_CN,
  'zh-TW': l_zh_TW,
};

export const localeCodes = Object.keys(locales);
